CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(32) NOT NULL,
    displayname VARCHAR(32),
    pfp VARCHAR(36) NOT NULL,
    bio VARCHAR(400) NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    passwd BINARY(60) NOT NULL,
    UNIQUE(username)
);
CREATE TABLE IF NOT EXISTS logins (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    session_id VARCHAR(36) NOT NULL,
    account_id BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS circles (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    parent_id BIGINT,
    owner_id BIGINT NOT NULL,
    name VARCHAR(64) NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    com_type TINYINT NOT NULL
);
CREATE TABLE IF NOT EXISTS insersections (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    a_id BIGINT NOT NULL,
    b_id BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS circle_members (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    account_id BIGINT NOT NULL,
    circle_id BIGINT NOT NULL,
    joined DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS posts (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    circle_id BIGINT NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(100) NOT NULL,
    body TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS media (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    name VARCHAR(36) NOT NULL,
    alt VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    circle_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    reply_id BIGINT,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    body VARCHAR(1000)
);